# Dockerfile_MYSQL

FROM mysql:5.7

#mysql 슈퍼관리자인 root ID에 대한 password란에 원하는 패스워드 설정
ENV MYSQL_ROOT_PASSWORD=password
#dbname란에 원하는 데이터베이스 이름 설정
ENV MYSQL_DATABASE=dbname

#필요시 다음 설정도 가능 
ENV MYSQL_USER=user 
#user 란에 mysql 추가 사용자 ID 설정 
ENV MYSQL_PASSWORD=pw 
# pw란에 mysql 추가 사용자 패스워드 설정 